```mermaid
erDiagram
direction LR
    CLIENTS {
        int client_id PK
        varchar name
        varchar email
        varchar password
    }

    MEETINGS {
        int meeting_id PK
        varchar topic
        int number_of_people
        date meeting_date
        int client_id FK
    }

    CLIENTS ||--o{ MEETINGS : "has many"
```